# Generated by Django 5.1.4 on 2025-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
